site_name: Mozilla Data Collective Python SDK
repo_url: https://github.com/Mozilla-Data-Collective/datacollective-python
repo_name: datacollective-python

nav:
  - Home: index.md
  - Schema-Based Loading: schema_parse.md
  - Loaders:
    - ASR: loaders/asr.md
    - TTS: loaders/tts.md
  - For Data Owners:
    - Adding a New Schema: add_new_schema.md
  - For Developers:
    - Extending Loading Logic: extend_schema_loading_logic.md
  - API Reference: api.md
  - Release Workflow: release.md

theme:
  icon:
    repo: fontawesome/brands/github
  name: material
  palette:
    - scheme: default
      primary: black
      toggle:
        icon: material/lightbulb
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode
  logo: docs/mdc_logo.png
  favicon: docs/mdc_ccc.png
  extra_css:
    - assets/custom.css
  features:
    - content.code.copy
    - content.tabs.link

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
plugins:
- search
- mkdocstrings:
    handlers:
      python:
        options:
          show_root_heading: true